export type Shell = "customer" | "business" | "admin";
export interface RouteDefinition {
  path: string;
  title: string;
  section: string;
  shell: Shell;
  staff?: "allow" | "forbidden";
}

const customer = [
  ["/", "Beranda", "Jelajah"],
  ["/venues", "Cari Venue", "Jelajah"],
  ["/venues/:slug", "Detail Venue", "Jelajah"],
  ["/venues/:slug/book", "Booking Lapangan", "Booking"],
  ["/checkout/:bookingId", "Checkout", "Booking"],
  ["/payments/:attemptId", "Pembayaran", "Booking"],
  ["/payments/:attemptId/result", "Hasil Pembayaran", "Booking"],
  ["/bookings", "Booking Saya", "Aktivitas"],
  ["/bookings/:id", "Detail Booking", "Aktivitas"],
  ["/mabar", "Daftar Mabar", "Komunitas"],
  ["/mabar/:id", "Detail Mabar", "Komunitas"],
  ["/mabar/create/:bookingId", "Buat Mabar", "Komunitas"],
  ["/mabar/:id/manage", "Kelola Mabar", "Komunitas"],
  ["/favorites", "Favorit", "Akun"],
  ["/history", "Riwayat Dilihat", "Akun"],
  ["/notifications", "Notifikasi", "Akun"],
  ["/reviews", "Review Saya", "Akun"],
  ["/support", "Tiket Bantuan", "Akun"],
  ["/profile", "Profil dan Pengaturan", "Akun"],
] as const;
const business = [
  ["/business/:tenant/overview", "Overview", "Beranda", "allow"],
  [
    "/business/:tenant/operations/calendar",
    "Kalender Operasional",
    "Operasional",
    "allow",
  ],
  ["/business/:tenant/operations/bookings", "Daftar Booking", "Operasional", "allow"],
  [
    "/business/:tenant/operations/bookings/new-offline",
    "Booking Offline",
    "Operasional",
    "allow",
  ],
  ["/business/:tenant/operations/check-in", "Check-in", "Operasional", "allow"],
  [
    "/business/:tenant/operations/outstanding",
    "Outstanding Payment",
    "Operasional",
    "allow",
  ],
  ["/business/:tenant/venues", "Kelola Venue", "Venue", "forbidden"],
  [
    "/business/:tenant/venues/:venueId/profile",
    "Profil dan Media",
    "Venue",
    "forbidden",
  ],
  ["/business/:tenant/venues/:venueId/courts", "Lapangan", "Venue", "forbidden"],
  [
    "/business/:tenant/venues/:venueId/availability",
    "Ketersediaan",
    "Venue",
    "forbidden",
  ],
  ["/business/:tenant/venues/:venueId/pricing", "Harga", "Venue", "forbidden"],
  ["/business/:tenant/venues/:venueId/policies", "Kebijakan", "Venue", "forbidden"],
  ["/business/:tenant/finance", "Ringkasan Keuangan", "Keuangan", "forbidden"],
  ["/business/:tenant/finance/transactions", "Transaksi", "Keuangan", "forbidden"],
  ["/business/:tenant/finance/refunds", "Refund dan Sengketa", "Keuangan", "forbidden"],
  ["/business/:tenant/finance/ledger", "Ledger", "Keuangan", "forbidden"],
  ["/business/:tenant/finance/payouts", "Payout Simulasi", "Keuangan", "forbidden"],
  ["/business/:tenant/growth/promotions", "Promosi", "Pertumbuhan", "forbidden"],
  ["/business/:tenant/growth/reviews", "Review", "Pertumbuhan", "allow"],
  ["/business/:tenant/growth/support", "Tiket", "Pertumbuhan", "allow"],
  ["/business/:tenant/growth/mabar", "Mabar di Venue", "Pertumbuhan", "allow"],
  ["/business/:tenant/team", "Tim", "Pengaturan", "forbidden"],
  ["/business/:tenant/notifications", "Notifikasi", "Pengaturan", "allow"],
  ["/business/:tenant/settings", "Pengaturan", "Pengaturan", "forbidden"],
] as const;
const admin = [
  ["/admin", "Dashboard Platform", "Platform"],
  ["/admin/customers", "Customer", "Akun"],
  ["/admin/tenants", "Owner dan Tenant", "Akun"],
  ["/admin/verifications", "Verifikasi Owner", "Verifikasi"],
  ["/admin/venues", "Venue", "Verifikasi"],
  ["/admin/masters/sports", "Master Olahraga", "Master"],
  ["/admin/masters/facilities", "Master Fasilitas", "Master"],
  ["/admin/masters/scheduling", "Interval dan Buffer", "Master"],
  ["/admin/templates/payments", "Template Pembayaran", "Kebijakan"],
  ["/admin/templates/refunds", "Template Refund", "Kebijakan"],
  ["/admin/templates/mabar", "Template Pembatalan Mabar", "Kebijakan"],
  ["/admin/commissions", "Komisi dan Trial", "Komersial"],
  ["/admin/promotions", "Promo Platform", "Komersial"],
  ["/admin/bookings", "Booking", "Operasional"],
  ["/admin/payments", "Pembayaran", "Keuangan"],
  ["/admin/refunds", "Refund dan Sengketa", "Keuangan"],
  ["/admin/finance", "Ledger Platform", "Keuangan"],
  ["/admin/payouts", "Payout Simulasi", "Keuangan"],
  ["/admin/reviews", "Review dan Laporan", "Moderasi"],
  ["/admin/support", "Tiket Bantuan", "Moderasi"],
  ["/admin/audit", "Audit Log", "Sistem"],
  ["/admin/config/notifications", "Konfigurasi Notifikasi", "Sistem"],
  ["/admin/system", "Status Integrasi dan Cron", "Sistem"],
] as const;

export const routeRegistry: RouteDefinition[] = [
  ...customer.map(([path, title, section]) => ({
    path,
    title,
    section,
    shell: "customer" as const,
  })),
  ...business.map(([path, title, section, staff]) => ({
    path,
    title,
    section,
    staff: staff as "allow" | "forbidden",
    shell: "business" as const,
  })),
  ...admin.map(([path, title, section]) => ({
    path,
    title,
    section,
    shell: "admin" as const,
  })),
];

export const criticalPaths = new Set([
  "/",
  "/venues",
  "/venues/:slug",
  "/venues/:slug/book",
  "/checkout/:bookingId",
  "/payments/:attemptId",
  "/payments/:attemptId/result",
  "/bookings",
  "/bookings/:id",
  "/mabar",
  "/mabar/:id",
  "/mabar/create/:bookingId",
  "/mabar/:id/manage",
  "/favorites",
  "/history",
  "/notifications",
  "/reviews",
  "/support",
  "/profile",
  "/business/:tenant/overview",
  "/business/:tenant/operations/calendar",
  "/business/:tenant/operations/bookings",
  "/business/:tenant/operations/bookings/new-offline",
  "/business/:tenant/operations/check-in",
  "/business/:tenant/operations/outstanding",
  "/business/:tenant/venues",
  "/business/:tenant/venues/:venueId/profile",
  "/business/:tenant/venues/:venueId/courts",
  "/business/:tenant/venues/:venueId/availability",
  "/business/:tenant/venues/:venueId/pricing",
  "/business/:tenant/venues/:venueId/policies",
  "/admin",
  "/admin/tenants",
  "/admin/verifications",
  "/admin/venues",
]);
