/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notificationId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["markNotificationRead"];
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["markAllNotificationsRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/link/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reauthenticate and start Google account linking. */
        post: operations["startGoogleAccountLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/venues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchVenues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/venues/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getVenue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCustomerBookings"];
        put?: never;
        post: operations["createBookingHold"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{bookingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBooking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment-attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPaymentAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment-attempts/{attemptId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPaymentAttempt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment-attempts/{attemptId}/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["simulatePaymentAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWorkspaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/pricing-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPriceRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/venues/{venueId}/media/signed-upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createVenueSignedUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/pricing-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["previewPricing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/masters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminMasters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/masters/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAdminNamedMaster"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/masters/{kind}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateAdminNamedMaster"];
        trace?: never;
    };
    "/admin/masters/durations/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAdminDurationOption"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/masters/payment-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAdminPaymentOption"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/masters/payment-options/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateAdminPaymentOption"];
        trace?: never;
    };
    "/business/tenants/transfer-primary-owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["transferPrimaryOwner"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/tenants/{tenantId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWorkspaceMembers"];
        put?: never;
        post: operations["addWorkspaceMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/tenants/{tenantId}/staff/{membershipId}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateStaffAssignments"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/setup-masters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBusinessSetupMasters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/venues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listBusinessVenues"];
        put?: never;
        post: operations["createBusinessVenue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/venues/{venueId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBusinessVenue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/venues/{venueId}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateBusinessVenueProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/venues/{venueId}/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateBusinessVenueCatalog"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/venues/{venueId}/courts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createBusinessCourt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/venues/{venueId}/courts/{courtId}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateCourtAvailability"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/venues/{venueId}/exceptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createScheduleException"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/venues/{venueId}/payment-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateVenuePaymentSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/venues/{venueId}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeVenueMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/venues/{venueId}/addons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createVenueAddon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/venues/{venueId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitBusinessVenue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBusinessDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listBusinessBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/bookings/offline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createOfflineBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/bookings/{bookingId}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["transitionBusinessBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/bookings/{bookingId}/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recordBusinessAttendance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/bookings/{bookingId}/settle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["settleBusinessOutstanding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/bookings/{bookingId}/cancel-for-closure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelBookingForClosure"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/bookings/{bookingId}/reschedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rescheduleBusinessBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/closures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createBusinessClosure"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBusinessCalendar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminTenants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tenants/{tenantId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateAdminTenantStatus"];
        trace?: never;
    };
    "/admin/venues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminVenues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/venues/{venueId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateAdminVenueStatus"];
        trace?: never;
    };
    "/admin/verifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminVerifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/verifications/{requestId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["decideAdminVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["subscribeEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Deterministically encrypted reference; internal numeric key is never exposed. */
        PublicId: string;
        /** @description Opaque random reference used in customer-facing booking URLs. */
        BookingReference: string;
        /** @description Opaque random reference used in customer-facing payment URLs. */
        PaymentReference: string;
        HealthResponse: {
            status: string;
            service: string;
        };
        ApiError: {
            code: string;
            message: string;
            details?: unknown;
            requestId: string;
        };
        RegisterInput: {
            name: string;
            /** Format: email */
            email: string;
            phone: string;
            password: string;
        };
        LoginInput: {
            /** Format: email */
            email: string;
            password: string;
        };
        SessionResponse: {
            user: {
                id: components["schemas"]["PublicId"];
                name: string;
                email: string;
            };
            memberships: {
                tenantId: components["schemas"]["PublicId"];
                /** @enum {string} */
                role: "PRIMARY_OWNER" | "OWNER" | "STAFF";
            }[];
            platformAdmin: boolean;
        };
        AccountNotification: {
            id: components["schemas"]["PublicId"];
            /** @enum {string} */
            kind: "booking" | "payment" | "verification" | "system";
            title: string;
            body: string;
            actionPath: string;
            read: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        Workspace: {
            tenantId: components["schemas"]["PublicId"];
            name: string;
            slug: string;
            status: string;
            /** @enum {string} */
            role: "PRIMARY_OWNER" | "OWNER" | "STAFF";
            membershipId: components["schemas"]["PublicId"];
            assignedVenueIds: components["schemas"]["PublicId"][];
        };
        WorkspaceMember: {
            membershipId: components["schemas"]["PublicId"];
            userId: components["schemas"]["PublicId"];
            name: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "PRIMARY_OWNER" | "OWNER" | "STAFF";
            status: string;
            assignedVenueIds: components["schemas"]["PublicId"][];
        };
        SetupProgress: {
            percentage: number;
            complete: boolean;
            sections: {
                [key: string]: boolean;
            };
        };
        VenueSetupSummary: {
            id: components["schemas"]["PublicId"];
            tenantId: components["schemas"]["PublicId"];
            name: string;
            slug: string;
            addressLine: string;
            status: string;
            publicationStatus: string;
            progress: components["schemas"]["SetupProgress"];
            revisionReason?: string | null;
        };
        VenueSetupDetail: components["schemas"]["VenueSetupSummary"] & {
            description: string;
            phoneE164: string;
            email?: string | null;
            provinceCode: string | null;
            cityCode: string | null;
            districtCode: string | null;
            postalCode: string | null;
            latitude?: string | null;
            longitude?: string | null;
            timezone: string;
            indoorOutdoorType: string;
            parkingInfo?: string | null;
            houseRules: string;
            emergencyContact: string | null;
            sportIds: components["schemas"]["PublicId"][];
            facilityIds: components["schemas"]["PublicId"][];
            mediaCount: number;
            courts: components["schemas"]["BusinessCourt"][];
            exceptions: {
                [key: string]: unknown;
            }[];
            blocks: {
                [key: string]: unknown;
            }[];
            priceRules: {
                [key: string]: unknown;
            }[];
            paymentSettings?: components["schemas"]["VenuePaymentSettings"] | null;
            addons: {
                [key: string]: unknown;
            }[];
        };
        BusinessCourt: {
            id: components["schemas"]["PublicId"];
            name: string;
            sportId: components["schemas"]["PublicId"];
            surface?: string | null;
            capacity?: number | null;
            status: string;
            settings?: {
                [key: string]: unknown;
            } | null;
            weeklySchedule: {
                [key: string]: unknown;
            }[];
        };
        SetupMasters: {
            sports: components["schemas"]["MasterOption"][];
            facilities: components["schemas"]["MasterOption"][];
            intervals: number[];
            buffers: number[];
        };
        MasterOption: {
            id: components["schemas"]["PublicId"];
            name: string;
        };
        VenueProfileInput: {
            tenantId: components["schemas"]["PublicId"];
            name: string;
            description: string;
            phoneE164: string;
            /** Format: email */
            email?: string;
            addressLine: string;
            provinceCode?: string;
            cityCode?: string;
            districtCode?: string;
            postalCode?: string;
            latitude: string;
            longitude: string;
            timezone: string;
            /** @enum {string} */
            indoorOutdoorType: "INDOOR" | "OUTDOOR" | "MIXED";
            parkingInfo?: string;
            houseRules: string;
            emergencyContact?: string;
        };
        CreateCourtInput: {
            tenantId: components["schemas"]["PublicId"];
            sportId: components["schemas"]["PublicId"];
            name: string;
            surface?: string;
            capacity?: number;
        };
        CourtAvailabilityInput: {
            tenantId: components["schemas"]["PublicId"];
            intervalMinutes: number;
            bufferMinutes: number;
            minimumDurationMinutes: number;
            maximumDurationMinutes: number;
            bookingWindowDays: number;
            minimumLeadMinutes: number;
            weeklySchedule: {
                dayOfWeek: number;
                opensAt: string;
                closesAt: string;
                active: boolean;
            }[];
        };
        ScheduleExceptionInput: {
            tenantId: components["schemas"]["PublicId"];
            courtId?: components["schemas"]["PublicId"];
            /** Format: date */
            localDate: string;
            /** @enum {string} */
            kind: "OPEN" | "CLOSED" | "CUSTOM_HOURS";
            opensAt?: string;
            closesAt?: string;
            reason?: string;
        };
        VenuePaymentSettings: {
            allowFull: boolean;
            allowDp: boolean;
            dpPercentage: number | null;
            allowPayAtVenue: boolean;
            reservationAmount: number | null;
            manualConfirmationMinutes: number;
            balanceDeadlineMinutes: number | null;
        };
        VenuePaymentSettingsInput: components["schemas"]["VenuePaymentSettings"] & {
            tenantId: components["schemas"]["PublicId"];
        };
        CreateSignedUploadInput: {
            tenantId: components["schemas"]["PublicId"];
            fileName: string;
            /** @enum {string} */
            mimeType: "image/webp" | "image/jpeg" | "image/png";
            byteSize: number;
        };
        SignedUpload: {
            storageKey: string;
            /** Format: uri */
            uploadUrl: string;
            expiresInSeconds: number;
        };
        CompleteVenueMediaInput: {
            tenantId: components["schemas"]["PublicId"];
            storageKey: string;
            /** @enum {string} */
            mimeType: "image/webp" | "image/jpeg" | "image/png";
            byteSize: number;
            altText: string;
            /** @enum {string} */
            purpose: "COVER" | "GALLERY";
        };
        CreatePriceRuleInput: {
            tenantId: components["schemas"]["PublicId"];
            venueId: components["schemas"]["PublicId"];
            courtId: string | null;
            /** @enum {string} */
            kind: "BASE" | "WEEKDAY_WEEKEND" | "DAY_TIME" | "SPECIAL_DATE";
            amount: number;
            dayOfWeek: number | null;
            /** Format: date */
            specialDate: string | null;
            startsAtLocal: string | null;
            endsAtLocal: string | null;
        };
        CustomerBookingSummary: components["schemas"]["Booking"] & {
            venueName: string;
            courtName: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
        };
        PricingPreviewInput: {
            tenantId: components["schemas"]["PublicId"];
            venueId: components["schemas"]["PublicId"];
            courtId: components["schemas"]["PublicId"];
            candidate?: components["schemas"]["CreatePriceRuleInput"];
            samples: {
                /** Format: date */
                localDate: string;
                localTime: string;
            }[];
        };
        PricingPreviewResult: {
            items: {
                /** Format: date */
                localDate: string;
                localTime: string;
                amount: number;
                /** @description Public rule ID, or `candidate` for an unsaved preview rule. */
                selectedRuleId: string;
                /** @enum {string} */
                selectedKind: "BASE" | "WEEKDAY_WEEKEND" | "DAY_TIME" | "SPECIAL_DATE";
                /** @enum {string} */
                scope: "COURT" | "VENUE";
            }[];
        };
        CreateOfflineBookingInput: components["schemas"]["CreateBookingInput"] & {
            tenantId: components["schemas"]["PublicId"];
            customer: {
                name: string;
                phone?: string;
                channel: string;
                adjustedAmount?: number;
                adjustmentReason?: string;
            };
        };
        BookingScope: {
            tenantId: components["schemas"]["PublicId"];
            venueId: components["schemas"]["PublicId"];
        };
        BookingTransitionInput: components["schemas"]["BookingScope"] & {
            status: string;
            reason: string;
        };
        AttendanceInput: components["schemas"]["BookingScope"] & {
            /** @enum {string} */
            attendance: "CHECKED_IN" | "NO_SHOW";
            reason?: string;
        };
        ClosureCancellationInput: components["schemas"]["BookingScope"] & {
            reason: string;
        };
        RescheduleInput: components["schemas"]["BookingScope"] & {
            newSlotIds: components["schemas"]["PublicId"][];
            reason: string;
        };
        CreateClosureInput: components["schemas"]["BookingScope"] & {
            courtId?: components["schemas"]["PublicId"];
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            /** @enum {string} */
            kind: "CLOSURE" | "MAINTENANCE" | "BLOCK";
            reason: string;
        };
        AdminNamedMaster: {
            id: components["schemas"]["PublicId"];
            slug: string;
            name: string;
            active: boolean;
        };
        AdminDurationOption: {
            id: components["schemas"]["PublicId"];
            minutes: number;
            active: boolean;
        };
        AdminPaymentOption: {
            id: components["schemas"]["PublicId"];
            code: string;
            label: string;
            active: boolean;
        };
        AdminMasters: {
            sports: components["schemas"]["AdminNamedMaster"][];
            facilities: components["schemas"]["AdminNamedMaster"][];
            bookingIntervals: components["schemas"]["AdminDurationOption"][];
            buffers: components["schemas"]["AdminDurationOption"][];
            paymentOptions: components["schemas"]["AdminPaymentOption"][];
        };
        BusinessBooking: {
            id: components["schemas"]["BookingReference"];
            venueId: components["schemas"]["PublicId"];
            venueName: string;
            courtId: components["schemas"]["PublicId"];
            courtName: string;
            customerName: string;
            customerPhone?: string | null;
            /** @enum {string} */
            source: "ONLINE" | "OFFLINE";
            status: string;
            paymentMode: string;
            paymentStatus: string;
            /** @enum {string|null} */
            attendanceStatus: "CHECKED_IN" | "NO_SHOW" | null;
            totalAmount: number;
            balanceDue: number;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            version: number;
        };
        BusinessDashboard: {
            bookingToday: number;
            pendingConfirmation: number;
            outstandingAmount: number;
            activeVenues: number;
            availableSlotsToday: number;
            upcoming: components["schemas"]["BusinessBooking"][];
            recentActivity: {
                bookingId: components["schemas"]["BookingReference"];
                status: string;
                reason?: string | null;
                /** Format: date-time */
                occurredAt: string;
            }[];
        };
        BusinessCalendar: {
            bookings: components["schemas"]["BusinessBooking"][];
            blocks: {
                id: components["schemas"]["PublicId"];
                venueId: components["schemas"]["PublicId"];
                courtId?: string | null;
                kind: string;
                /** Format: date-time */
                startsAt: string;
                /** Format: date-time */
                endsAt: string;
                reason: string;
            }[];
        };
        AdminDashboard: {
            users: number;
            tenants: number;
            activeVenues: number;
            pendingVerifications: number;
            bookings: number;
            sandboxVolume: number;
            pendingOutbox: number;
        };
        AdminAuditEntry: {
            id: components["schemas"]["PublicId"];
            action: string;
            resourceType: string;
            resourceId: string | null;
            actor: {
                id?: components["schemas"]["PublicId"];
                name?: string;
                /** Format: email */
                email?: string;
            } | null;
            tenant: {
                id?: components["schemas"]["PublicId"];
                name?: string;
            } | null;
            venue: {
                id?: components["schemas"]["PublicId"];
                name?: string;
            } | null;
            reason: string | null;
            beforeState: unknown;
            afterState: unknown;
            requestId: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        AdminAuditPage: {
            items: components["schemas"]["AdminAuditEntry"][];
            nextCursor: string | null;
        };
        AdminTenant: {
            id: components["schemas"]["PublicId"];
            name: string;
            slug: string;
            status: string;
            primaryOwner?: string | null;
            primaryOwnerEmail?: string | null;
            venueCount: number;
        };
        AdminVenue: {
            id: components["schemas"]["PublicId"];
            tenantId: components["schemas"]["PublicId"];
            tenantName: string;
            name: string;
            slug: string;
            addressLine: string;
            status: string;
            publicationStatus: string;
        };
        AdminVerification: {
            requestId: components["schemas"]["PublicId"];
            venueId: components["schemas"]["PublicId"];
            venueName: string;
            tenantId: components["schemas"]["PublicId"];
            tenantName: string;
            status: string;
            venueVersion: number;
            reason?: string | null;
            snapshot: unknown;
            /** Format: date-time */
            submittedAt: string;
            /** Format: date-time */
            decidedAt?: string | null;
        };
        AdminStatusChangeInput: {
            /** @enum {string} */
            status: "DRAFT" | "ACTIVE" | "INACTIVE" | "SUSPENDED";
            reason: string;
        };
        Venue: {
            id: components["schemas"]["PublicId"];
            slug: string;
            name: string;
            location: string;
            cityCode: string | null;
            /** @enum {string} */
            indoorOutdoorType: "INDOOR" | "OUTDOOR" | "MIXED";
            sport: string;
            sports: string[];
            rating: number;
            reviewCount: number;
            priceFrom: number;
            hasPromo: boolean;
            promoLabel?: string | null;
            /** Format: date-time */
            nearestSlotStartsAt: string | null;
            paymentModes: ("FULL" | "DP" | "PAY_AT_VENUE")[];
            distanceKm: number | null;
            latitude?: number | null;
            longitude?: number | null;
            imageUrl?: string | null;
            description?: string;
            galleryUrls?: string[];
            parkingInfo?: string | null;
            houseRules?: string | null;
            timezone?: string;
            facilities?: components["schemas"]["PublicId"][];
            courts?: components["schemas"]["CourtSummary"][];
            addons?: components["schemas"]["VenueAddon"][];
        };
        VenueAddon: {
            id: components["schemas"]["PublicId"];
            name: string;
            price: number;
        };
        CourtSummary: {
            id: components["schemas"]["BookingReference"];
            name: string;
            sport: string;
            surface?: string | null;
        };
        VenuePage: {
            items: components["schemas"]["Venue"][];
            nextCursor?: components["schemas"]["PublicId"] | null;
        };
        AvailabilitySlot: {
            id: components["schemas"]["PublicId"];
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            price: number;
            /** @enum {string} */
            status: "AVAILABLE" | "HELD" | "BOOKED" | "BLOCKED";
        };
        CreateBookingInput: {
            venueId: components["schemas"]["PublicId"];
            courtId: components["schemas"]["PublicId"];
            slotIds: components["schemas"]["PublicId"][];
            addonIds?: string[];
            /** @enum {string} */
            paymentMode: "FULL" | "DP" | "PAY_AT_VENUE";
        };
        Booking: {
            id: components["schemas"]["PublicId"];
            venueId: components["schemas"]["PublicId"];
            /** @enum {string} */
            paymentMode: "FULL" | "DP" | "PAY_AT_VENUE";
            /** @enum {string} */
            status: "HOLD" | "PENDING_CONFIRMATION" | "CONFIRMED" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED" | "EXPIRED";
            /** @enum {string} */
            paymentStatus: "UNPAID" | "PARTIALLY_PAID" | "PAID" | "PARTIALLY_REFUNDED" | "REFUNDED";
            totalAmount: number;
            balanceDue: number;
            /** Format: date-time */
            holdExpiresAt: string | null;
            version: number;
        };
        PaymentAttempt: {
            id: components["schemas"]["PaymentReference"];
            bookingId: components["schemas"]["BookingReference"];
            kind: string;
            amount: number;
            /** @enum {string} */
            status: "CREATED" | "PENDING" | "PAID" | "FAILED" | "EXPIRED" | "CANCELLED";
            redirectUrl?: string | null;
            /** @constant */
            sandbox: true;
        };
    };
    responses: {
        /** @description Authentication is required. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description The active identity cannot access this workspace resource. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description State or reservation conflict. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Request validation failed. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description JSON request body exceeds the global 1 MB limit. */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Internal service error. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        Cursor: string;
        Limit: number;
        IdempotencyKey: string;
        TenantId: components["schemas"]["PublicId"];
        BookingId: components["schemas"]["BookingReference"];
        TenantIdQuery: components["schemas"]["PublicId"];
        VenueId: components["schemas"]["PublicId"];
        VenueIdQuery: components["schemas"]["PublicId"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dependencies are ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterInput"];
            };
        };
        responses: {
            /** @description User and session created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            /** @description Session created. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    listNotifications: {
        parameters: {
            query?: {
                unreadOnly?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notification feed for the active customer account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AccountNotification"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    markNotificationRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationId: components["schemas"]["PublicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notification marked as read. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    markAllNotificationsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All account notifications marked as read. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session ended. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    startGoogleAccountLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    password: string;
                };
            };
        };
        responses: {
            /** @description Short-lived Google authorization URL. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uri */
                        authorizationUrl: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            413: components["responses"]["PayloadTooLarge"];
            503: components["responses"]["InternalError"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active identity and workspaces. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    searchVenues: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                query?: string;
                area?: string;
                cityCode?: string;
                sport?: string;
                /** @description Daftar slug fasilitas dipisahkan koma; seluruh fasilitas wajib tersedia. */
                facilities?: string;
                date?: string;
                time?: string;
                minimumPrice?: number;
                maximumPrice?: number;
                indoorOutdoorType?: "INDOOR" | "OUTDOOR" | "MIXED";
                paymentMode?: "FULL" | "DP" | "PAY_AT_VENUE";
                hasPromo?: boolean;
                minimumRating?: number;
                latitude?: number;
                longitude?: number;
                maximumDistanceKm?: number;
                sort?: "RELEVANT" | "NEAREST" | "PRICE_LOWEST" | "RATING_HIGHEST" | "POPULAR" | "NEWEST";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VenuePage"];
                };
            };
        };
    };
    getVenue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["schemas"]["PublicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Venue detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Venue"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getAvailability: {
        parameters: {
            query: {
                courtId: components["schemas"]["BookingReference"];
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authoritative slots and price previews. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AvailabilitySlot"][];
                        version: number;
                    };
                };
            };
        };
    };
    listCustomerBookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bookings owned by the authenticated customer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["CustomerBookingSummary"][];
                    };
                };
            };
        };
    };
    createBookingHold: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingInput"];
            };
        };
        responses: {
            /** @description Booking hold created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationError"];
        };
    };
    getBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Booking snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createPaymentAttempt: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    bookingId: components["schemas"]["BookingReference"];
                    /** @enum {string} */
                    kind: "FULL" | "DP" | "RESERVATION" | "BALANCE";
                };
            };
        };
        responses: {
            /** @description Sandbox payment attempt created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentAttempt"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    getPaymentAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payment attempt snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentAttempt"];
                };
            };
        };
    };
    simulatePaymentAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    result: "success" | "pending" | "failed" | "expired";
                };
            };
        };
        responses: {
            /** @description Sandbox result accepted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    listWorkspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active business workspaces for the current identity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Workspace"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Draft tenant and Primary Owner membership created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationError"];
        };
    };
    createPriceRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePriceRuleInput"];
            };
        };
        responses: {
            /** @description Price rule created after overlap validation. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: components["schemas"]["PublicId"];
                    };
                };
            };
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    createVenueSignedUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venueId: components["parameters"]["VenueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSignedUploadInput"];
            };
        };
        responses: {
            /** @description Short-lived object storage upload URL scoped to an Owner venue. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignedUpload"];
                };
            };
            403: components["responses"]["Forbidden"];
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    listAdminAudit: {
        parameters: {
            query?: {
                cursor?: components["schemas"]["PublicId"];
                limit?: number;
                action?: string;
                resourceType?: string;
                tenantId?: components["schemas"]["PublicId"];
                venueId?: components["schemas"]["PublicId"];
                actorUserId?: components["schemas"]["PublicId"];
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable platform activity explorer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAuditPage"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    previewPricing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PricingPreviewInput"];
            };
        };
        responses: {
            /** @description Resolved price and selected rule for every sample. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricingPreviewResult"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationError"];
        };
    };
    getAdminMasters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Platform master configuration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMasters"];
                };
            };
        };
    };
    createAdminNamedMaster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "sport" | "facility";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Master option created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    updateAdminNamedMaster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "sport" | "facility";
                id: components["schemas"]["PublicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    active: boolean;
                };
            };
        };
        responses: {
            /** @description Master active state updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    createAdminDurationOption: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "interval" | "buffer";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    minutes: number;
                };
            };
        };
        responses: {
            /** @description Duration option created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    createAdminPaymentOption: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    code: string;
                    label: string;
                };
            };
        };
        responses: {
            /** @description Payment option created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    updateAdminPaymentOption: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["PublicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    active: boolean;
                };
            };
        };
        responses: {
            /** @description Payment option active state updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    transferPrimaryOwner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    tenantId: components["schemas"]["PublicId"];
                    targetMembershipId: components["schemas"]["PublicId"];
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Primary Owner transferred transactionally. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    listWorkspaceMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant membership and Staff assignments. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["WorkspaceMember"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    addWorkspaceMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    /** @enum {string} */
                    role: "OWNER" | "STAFF";
                };
            };
        };
        responses: {
            /** @description Existing registered user added to workspace. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        membershipId: components["schemas"]["PublicId"];
                    };
                };
            };
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    updateStaffAssignments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["TenantId"];
                membershipId: components["schemas"]["PublicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    venueIds: components["schemas"]["PublicId"][];
                };
            };
        };
        responses: {
            /** @description Assignments replaced. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    getBusinessSetupMasters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active master configuration for venue setup. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupMasters"];
                };
            };
        };
    };
    listBusinessVenues: {
        parameters: {
            query: {
                tenantId: components["parameters"]["TenantIdQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Venues visible in the active workspace. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["VenueSetupSummary"][];
                    };
                };
            };
        };
    };
    createBusinessVenue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    tenantId: components["schemas"]["PublicId"];
                    name: string;
                };
            };
        };
        responses: {
            /** @description Private venue draft created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: components["schemas"]["PublicId"];
                        slug: string;
                    };
                };
            };
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    getBusinessVenue: {
        parameters: {
            query: {
                tenantId: components["parameters"]["TenantIdQuery"];
            };
            header?: never;
            path: {
                venueId: components["parameters"]["VenueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Complete venue setup read model. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VenueSetupDetail"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateBusinessVenueProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venueId: components["parameters"]["VenueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VenueProfileInput"];
            };
        };
        responses: {
            /** @description Profile saved. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    updateBusinessVenueCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venueId: components["parameters"]["VenueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    tenantId: components["schemas"]["PublicId"];
                    sportIds: components["schemas"]["PublicId"][];
                    facilityIds: components["schemas"]["PublicId"][];
                };
            };
        };
        responses: {
            /** @description Venue sports and facilities replaced. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    createBusinessCourt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venueId: components["parameters"]["VenueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCourtInput"];
            };
        };
        responses: {
            /** @description Court created with default booking settings. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: components["schemas"]["PublicId"];
                    };
                };
            };
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    updateCourtAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venueId: components["parameters"]["VenueId"];
                courtId: components["schemas"]["PublicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourtAvailabilityInput"];
            };
        };
        responses: {
            /** @description Schedule and booking constraints replaced. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    createScheduleException: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venueId: components["parameters"]["VenueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleExceptionInput"];
            };
        };
        responses: {
            /** @description Exception created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: components["schemas"]["PublicId"];
                    };
                };
            };
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    updateVenuePaymentSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venueId: components["parameters"]["VenueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VenuePaymentSettingsInput"];
            };
        };
        responses: {
            /** @description Payment settings saved. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    completeVenueMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venueId: components["parameters"]["VenueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteVenueMediaInput"];
            };
        };
        responses: {
            /** @description Uploaded asset linked to venue. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: components["schemas"]["PublicId"];
                    };
                };
            };
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    createVenueAddon: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venueId: components["parameters"]["VenueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    tenantId: components["schemas"]["PublicId"];
                    name: string;
                    price: number;
                };
            };
        };
        responses: {
            /** @description Add-on created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    submitBusinessVenue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venueId: components["parameters"]["VenueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    tenantId: components["schemas"]["PublicId"];
                };
            };
        };
        responses: {
            /** @description Versioned verification request created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        requestId: components["schemas"]["PublicId"];
                    };
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationError"];
        };
    };
    getBusinessDashboard: {
        parameters: {
            query: {
                tenantId: components["parameters"]["TenantIdQuery"];
                venueId?: components["parameters"]["VenueIdQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operational summary scoped by membership and assignment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessDashboard"];
                };
            };
        };
    };
    listBusinessBookings: {
        parameters: {
            query: {
                tenantId: components["parameters"]["TenantIdQuery"];
                venueId?: components["parameters"]["VenueIdQuery"];
                startsAfter?: string;
                startsBefore?: string;
                status?: string;
                outstandingOnly?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Booking list scoped by tenant membership. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["BusinessBooking"][];
                    };
                };
            };
        };
    };
    createOfflineBooking: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOfflineBookingInput"];
            };
        };
        responses: {
            /** @description Offline booking reserved by the shared booking transaction. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    transitionBusinessBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingTransitionInput"];
            };
        };
        responses: {
            /** @description Valid booking transition recorded. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    recordBusinessAttendance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttendanceInput"];
            };
        };
        responses: {
            /** @description Check-in or no-show recorded. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    settleBusinessOutstanding: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingScope"];
            };
        };
        responses: {
            /** @description Sandbox venue settlement recorded as a payment attempt. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        attemptId: components["schemas"]["PaymentReference"];
                        amount: number;
                    };
                };
            };
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    cancelBookingForClosure: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClosureCancellationInput"];
            };
        };
        responses: {
            /** @description Booking cancelled with compatible refund record. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    rescheduleBusinessBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RescheduleInput"];
            };
        };
        responses: {
            /** @description New slots locked before old reservation release. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    createBusinessClosure: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClosureInput"];
            };
        };
        responses: {
            /** @description Closure and impacted booking references. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        blockId: components["schemas"]["PublicId"];
                        impactedBookingIds: components["schemas"]["BookingReference"][];
                    };
                };
            };
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    getBusinessCalendar: {
        parameters: {
            query: {
                tenantId: components["parameters"]["TenantIdQuery"];
                venueId?: components["parameters"]["VenueIdQuery"];
                startsAfter: string;
                startsBefore: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Booking and block calendar read model. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessCalendar"];
                };
            };
        };
    };
    getAdminDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Platform sandbox metrics and integration status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDashboard"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listAdminTenants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant review list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AdminTenant"][];
                    };
                };
            };
        };
    };
    updateAdminTenantStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminStatusChangeInput"];
            };
        };
        responses: {
            /** @description Tenant lifecycle status updated and audited. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    listAdminVenues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cross-tenant venue list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AdminVenue"][];
                    };
                };
            };
        };
    };
    updateAdminVenueStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venueId: components["parameters"]["VenueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminStatusChangeInput"];
            };
        };
        responses: {
            /** @description Venue lifecycle status updated and audited. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    listAdminVerifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification queue and immutable snapshots. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AdminVerification"][];
                    };
                };
            };
        };
    };
    decideAdminVerification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: components["schemas"]["PublicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    decision: "APPROVED" | "REJECTED" | "REVISION_REQUIRED";
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Decision recorded. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    subscribeEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated server-sent event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
}
